#ifndef CLI_CONTROLLER_SRC
#define CLI_CONTROLLER_SRC

#include "controller.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <FreeRTOS.h>
#include <task.h>
#include <FreeRTOS_CLI.h>

#include "protocols/UART.h"
#include "stm32/STM32.h"
#include "core/system_configuration.h"

/* Dimensions the buffer into which input characters are placed. */
#define cmdMAX_INPUT_SIZE	60

/* Dimensions the buffer into which string outputs can be placed. */
#define cmdMAX_OUTPUT_SIZE	1024

/* Dimensions the buffer passed to the recvfrom() call. */
#define cmdSOCKET_INPUT_BUFFER_SIZE 60

/* DEL acts as a backspace. */
#define cmdASCII_DEL		( 0x7F )

static xTaskHandle handle;




// ----- Case functions implementation ----- //
OPTION_FUNCTION_IMPL(general, help)
{
    uart6_transmit_line(GENERAL_USAGE);
    return true;
}

OPTION_FUNCTION_IMPL(general, save)
{
    return true;
}

OPTION_FUNCTION_IMPL(general, start)
{
    vTaskSuspend(NULL);
    return true;
}


OPTION_FUNCTION_IMPL(general, test)
{
    return true;
}

void prv_cli_function(void * pvParams)
{
    uart6_transmit_line(INTRO_USAGE);
    general_help_function(NULL);

    long lBytes, lByte;
    signed char cInChar, cInputIndex = 0;
    static char cInputString[ cmdMAX_INPUT_SIZE ], cOutputString[ cmdMAX_OUTPUT_SIZE ], cLocalBuffer[ cmdSOCKET_INPUT_BUFFER_SIZE ];
    BaseType_t xMoreDataToFollow;
    volatile int iErrorCode = 0;

    /* As per most FreeRTOS tasks, this task is implemented in an infinite loop. */
    while(1)
    {
        /* Process the input string received prior to the newline. */
        DISPLAY(">>", NULL);
        INPUT(cInputString);
        do
        {
            /* Pass the string to FreeRTOS+CLI. */
            xMoreDataToFollow = FreeRTOS_CLIProcessCommand( cInputString, cOutputString, cmdMAX_OUTPUT_SIZE );

            /* Send the output generated by the command's implementation. */
            const char * cOutputStringP = cOutputString;
            DISPLAY("%s", cOutputStringP);

        } while( xMoreDataToFollow != pdFALSE ); /* Until the command does not generate any more output. */

        /* All the strings generated by the command processing
        have been sent.  Clear the input string ready to receive
        the next command. */
        cInputIndex = 0;
        memset( cInputString, 0x00, cmdMAX_INPUT_SIZE );
    }
}

void command_line_interface_start(void *pvParameters)
{
    if(pdFALSE == xTaskCreate(prv_cli_function, "cli-task", configMINIMAL_STACK_SIZE, NULL, 5, NULL))
    {
        stm32_error_handler(__FILE__, __LINE__);
    }
}







#endif // CLI_CONTROLLER_SRC

